const ADMIN_EMAIL='a81650448@gmail.com';
const db=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id); let orders=[],medicines=[];
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const money=v=>'₹'+Number(v||0).toFixed(2);
function msg(t,ok=true){const x=$('msg');x.textContent=t;x.className='card '+(ok?'success':'danger');setTimeout(()=>x.classList.add('hidden'),3000)}
function expiry(d){if(!d)return ['Not set',''];const a=new Date(d+'T00:00:00'),b=new Date();b.setHours(0,0,0,0);const n=Math.ceil((a-b)/86400000);if(n<0)return [`Expired (${Math.abs(n)} days ago)`,'expired'];if(n<=30)return [`Expires in ${n} days`,'low'];return [d,'']}
async function loadAll(){await loadOrders();await loadMedicines()}
async function loadOrders(){const r=await db.from('orders').select('*').order('created_at',{ascending:false});if(r.error){msg('Unable to load orders: '+r.error.message,false);return}orders=r.data||[];renderOrders();renderCustomers();renderPayments();renderDelivery();renderReports();renderNotifications()}
function renderOrders(){const q=($('orderSearch').value||'').toLowerCase();const a=orders.filter(o=>`${o.order_id} ${o.customer_name} ${o.phone}`.toLowerCase().includes(q));$('ordersBody').innerHTML=a.length?a.map(o=>`<tr><td><b>${esc(o.order_id)}</b></td><td>${esc(o.customer_name)}<br>${esc(o.phone)}<br>${esc(o.address)}</td><td>${Array.isArray(o.items)?o.items.map(i=>`${esc(i.name)} × ${Number(i.qty||0)}`).join('<br>'):'—'}</td><td>${money(o.total)}</td><td>${esc(o.payment_method)}${o.transaction_id?'<br>UTR: '+esc(o.transaction_id):''}</td><td><select class="select status" data-id="${o.id}"><option ${o.status==='Pending'?'selected':''}>Pending</option><option ${o.status==='Confirmed'?'selected':''}>Confirmed</option><option ${o.status==='Packed'?'selected':''}>Packed</option><option ${o.status==='Out for Delivery'?'selected':''}>Out for Delivery</option><option ${o.status==='Delivered'?'selected':''}>Delivered</option><option ${o.status==='Cancelled'?'selected':''}>Cancelled</option></select></td><td>${new Date(o.created_at).toLocaleString('en-IN')}</td><td>${o.status==='Delivered'?`<button class="btn danger delete" data-id="${o.id}" type="button">🗑️ Delete</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="8">No orders found.</td></tr>';$('sTotal').textContent=orders.length;$('sPending').textContent=orders.filter(o=>o.status==='Pending').length;$('sDelivered').textContent=orders.filter(o=>o.status==='Delivered').length;$('sSales').textContent=money(orders.reduce((s,o)=>s+Number(o.total||0),0));document.querySelectorAll('.status').forEach(e=>e.onchange=()=>updateStatus(e.dataset.id,e.value));document.querySelectorAll('.delete').forEach(e=>e.onclick=()=>deleteOrder(e.dataset.id))}
async function updateStatus(id,status){const r=await db.from('orders').update({status}).eq('id',id);if(r.error){msg('Status update failed: '+r.error.message,false);return}msg('Order status updated');loadOrders()}
async function deleteOrder(id){const o=orders.find(x=>String(x.id)===String(id));if(!o||o.status!=='Delivered')return;if(!confirm(`Delete delivered order ${o.order_id}?`))return;const r=await db.from('orders').delete().eq('id',id).eq('status','Delivered');if(r.error){msg('Delete failed: '+r.error.message,false);return}msg('Order deleted');loadOrders()}
async function loadMedicines(){const r=await db.from('medicines').select('*').order('name');if(r.error){$('medicinesBody').innerHTML='<tr><td colspan="7">Medicine table not available.</td></tr>';return}medicines=r.data||[];renderMedicines()}
function renderMedicines(){const q=($('medicineSearch').value||'').toLowerCase();const a=medicines.filter(m=>`${m.name} ${m.category||''} ${m.manufacturer||''}`.toLowerCase().includes(q));$('medicinesBody').innerHTML=a.length?a.map(m=>{const e=expiry(m.expiry_date||m.expiry);return `<tr><td>${esc(m.name)}</td><td>${esc(m.category)}</td><td>${money(m.price)}</td><td><b>${Number(m.stock||0)}</b></td><td>${esc(m.manufacturer)}</td><td><span class="pill ${e[1]}">${esc(e[0])}</span></td><td><button class="btn danger med-delete" data-id="${m.id}" type="button">Delete</button></td></tr>`}).join(''):'<tr><td colspan="7">No medicines found.</td></tr>';document.querySelectorAll('.med-delete').forEach(e=>e.onclick=()=>deleteMedicine(e.dataset.id));renderInventory();renderNotifications()}
function renderInventory(){const a=[...medicines].sort((x,y)=>Number(x.stock||0)-Number(y.stock||0));$('inventoryBody').innerHTML=a.length?a.map(m=>{const s=Number(m.stock||0),e=expiry(m.expiry_date||m.expiry),st=s===0?'Out of Stock':s<10?'Low Stock':'Available';return `<div class="card"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><div><b>${esc(m.name)}</b><br><span class="muted">${esc(m.category||'')} · ${e[0]}</span></div><div class="stock-actions"><button class="btn" data-stock="${m.id}" data-change="-1" type="button">−</button><strong>${s}</strong><button class="btn" data-stock="${m.id}" data-change="1" type="button">+</button><span class="pill ${s===0?'expired':s<10?'low':''}">${st}</span></div></div></div>`}).join(''):'No medicines.';document.querySelectorAll('[data-stock]').forEach(e=>e.onclick=()=>adjustStock(e.dataset.stock,Number(e.dataset.change)))}
async function adjustStock(id,c){const m=medicines.find(x=>String(x.id)===String(id));if(!m)return;const next=Math.max(0,Number(m.stock||0)+c),r=await db.from('medicines').update({stock:next}).eq('id',id);if(r.error){msg('Stock update failed: '+r.error.message,false);return}msg('Stock updated');loadMedicines()}
async function deleteMedicine(id){if(!confirm('Delete this medicine?'))return;const r=await db.from('medicines').delete().eq('id',id);if(r.error){msg('Medicine delete failed: '+r.error.message,false);return}msg('Medicine deleted');loadMedicines()}
async function addMedicine(){const row={name:$('mName').value.trim(),category:$('mCategory').value.trim(),price:Number($('mPrice').value||0),stock:Math.max(0,Number($('mStock').value||0)),manufacturer:$('mManufacturer').value.trim(),expiry_date:$('mExpiry').value||null};if(!row.name){msg('Medicine name is required.',false);return}const r=await db.from('medicines').insert(row);if(r.error){msg('Could not add medicine: '+r.error.message,false);return}document.querySelectorAll('#medicines input').forEach(e=>e.value='');msg('Medicine added');loadMedicines()}
function renderCustomers(){const m={};orders.forEach(o=>{const k=o.phone||o.customer_name;if(!m[k])m[k]={name:o.customer_name,phone:o.phone,address:o.address,count:0,total:0};m[k].count++;m[k].total+=Number(o.total||0)});const q=($('customerSearch').value||'').toLowerCase();$('customersBody').innerHTML=Object.values(m).filter(c=>`${c.name} ${c.phone}`.toLowerCase().includes(q)).map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${esc(c.address)}</td><td>${c.count}</td><td>${money(c.total)}</td></tr>`).join('')||'<tr><td colspan="5">No customers found.</td></tr>'}
function renderPayments(){$('paymentsBody').innerHTML=orders.map(o=>`<tr><td>${esc(o.order_id)}</td><td>${esc(o.customer_name)}</td><td>${esc(o.payment_method)}</td><td>${money(o.total)}</td><td>${esc(o.transaction_id||'—')}</td><td>${esc(o.status)}</td></tr>`).join('')||'<tr><td colspan="6">No payments.</td></tr>'}
function renderDelivery(){$('deliveryBody').innerHTML=orders.filter(o=>!['Delivered','Cancelled'].includes(o.status)).map(o=>`<tr><td>${esc(o.order_id)}</td><td>${esc(o.customer_name)}</td><td>${esc(o.phone)}</td><td>${esc(o.address)}</td><td>${esc(o.status)}</td></tr>`).join('')||'<tr><td colspan="5">No active deliveries.</td></tr>'}
function renderReports(){const s=orders.reduce((a,o)=>a+Number(o.total||0),0);$('rOrders').textContent=orders.length;$('rSales').textContent=money(s);$('rAvg').textContent=money(orders.length?s/orders.length:0);$('rDelivered').textContent=orders.filter(o=>o.status==='Delivered').length}
function renderNotifications(){const low=medicines.filter(m=>Number(m.stock||0)<10),ex=medicines.filter(m=>expiry(m.expiry_date||m.expiry)[1]==='expired'),soon=medicines.filter(m=>expiry(m.expiry_date||m.expiry)[1]==='low'),p=orders.filter(o=>o.status==='Pending');$('notificationsBody').innerHTML=`<div class="alert">🔴 ${p.length} pending order(s)</div><div class="alert">🟡 ${low.length} low/out-of-stock medicine(s)</div><div class="alert">⚠️ ${ex.length} expired medicine(s)</div><div class="alert">📅 ${soon.length} medicine(s) expire within 30 days</div>`;const issues=[...low.map(m=>`🟡 <b>${esc(m.name)}</b>: ${Number(m.stock||0)} in stock`),...ex.map(m=>`🔴 <b>${esc(m.name)}</b>: expired`),...soon.map(m=>`📅 <b>${esc(m.name)}</b>: ${expiry(m.expiry_date||m.expiry)[0]}`)];$('lowStock').innerHTML=issues.length?issues.map(x=>`<p>${x}</p>`).join(''):'No stock or expiry alerts.'}
function csv(){const rows=[['Order ID','Customer','Phone','Total','Payment','Status','Date'],...orders.map(o=>[o.order_id,o.customer_name,o.phone,o.total,o.payment_method,o.status,o.created_at])];const b=new Blob([rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='seema-medical-store-orders.csv';a.click()}
function setupBillingUI(){
  const side=document.querySelector('.side');
  const main=document.querySelector('.main');
  if(!side||!main||document.querySelector('[data-section="billing"]'))return;
  const b=document.createElement('button');b.type='button';b.dataset.section='billing';b.textContent='🧾 Billing';side.appendChild(b);
  const s=document.createElement('section');s.id='billing';s.className='section';s.innerHTML=`<h2>Billing & Invoices</h2><div class="card"><h3>Billing Module</h3><p>Billing database is connected and ready.</p><p><b>Next:</b> New Offline Sale, Online Order → Bill, Print/Download Bill and Bill History.</p><p class="muted">No existing order, medicine or login data is changed in this step.</p></div>`;main.appendChild(s);
  b.onclick=()=>{document.querySelectorAll('.side button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));s.classList.add('active')};
}
async function showApp(){ $('loginCard').classList.add('hidden');$('app').classList.remove('hidden');setupBillingUI();await loadAll()}
async function checkLogin(){const r=await db.auth.getSession();if(r.error){$('loginError').textContent=r.error.message;$('loginError').classList.remove('hidden');return}const s=r.data.session;if(s&&s.user.email?.toLowerCase()===ADMIN_EMAIL.toLowerCase())showApp();else{$('loginCard').classList.remove('hidden');$('app').classList.add('hidden')}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const er=$('loginError');er.classList.add('hidden');const email=$('email').value.trim(),password=$('password').value;if(email.toLowerCase()!==ADMIN_EMAIL.toLowerCase()){er.textContent='Please use the authorized admin email.';er.classList.remove('hidden');return}const r=await db.auth.signInWithPassword({email,password});if(r.error){er.textContent=r.error.message;er.classList.remove('hidden');return}await showApp()});
$('logoutBtn').onclick=async()=>{await db.auth.signOut();location.reload()};
document.querySelectorAll('.side button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.side button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));$(b.dataset.section).classList.add('active')});
$('orderSearch').oninput=renderOrders;$('medicineSearch').oninput=renderMedicines;$('customerSearch').oninput=renderCustomers;$('addMedicine').onclick=addMedicine;$('downloadCsv').onclick=csv;checkLogin();