(function(){'use strict';
const ADMIN_APPT_STYLE=`<style id="appointmentAdminStyle">#appointments .appt-toolbar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:12px}.appt-status{padding:5px 8px;border-radius:8px;border:1px solid #d0d5dd}.appt-note{min-width:180px}.appt-actions{display:flex;gap:6px;flex-wrap:wrap}.appt-dashboard-card{cursor:pointer}.appt-dashboard-card:hover{transform:translateY(-1px)}</style>`;
function escA(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function apptDb(){return window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);}
async function loadAppointments(){const body=document.getElementById('appointmentsBody');if(!body)return;body.innerHTML='<tr><td colspan="8">Loading appointments...</td></tr>';const r=await apptDb().from('appointments').select('*').order('appointment_date',{ascending:true}).order('appointment_time',{ascending:true});if(r.error){body.innerHTML='<tr><td colspan="8">Unable to load appointments: '+escA(r.error.message)+'</td></tr>';return;}const rows=r.data||[];const pending=rows.filter(a=>(a.status||'Pending')==='Pending').length;const pc=document.getElementById('appointmentPendingCount');if(pc)pc.textContent=pending;body.innerHTML=rows.length?rows.map(a=>`<tr><td><b>${escA(a.appointment_id)}</b></td><td>${escA(a.patient_name)}<br>${escA(a.phone)}${a.email?'<br>'+escA(a.email):''}</td><td>${escA(a.doctor)}</td><td>${escA(a.appointment_date)}<br>${escA(a.appointment_time)}</td><td>${escA(a.reason||'—')}</td><td><select class="appt-status" data-appt-id="${escA(a.id)}"><option ${a.status==='Pending'||!a.status?'selected':''}>Pending</option><option ${a.status==='Confirmed'?'selected':''}>Confirmed</option><option ${a.status==='Completed'?'selected':''}>Completed</option><option ${a.status==='Cancelled'?'selected':''}>Cancelled</option></select></td><td><input class="input appt-note" data-note-id="${escA(a.id)}" value="${escA(a.admin_notes||'')}" placeholder="Admin notes"></td><td><div class="appt-actions"><button class="btn primary appt-save" data-id="${escA(a.id)}">Save</button><button class="btn danger appt-delete" data-id="${escA(a.id)}">Delete</button></div></td></tr>`).join(''):'<tr><td colspan="8">No appointments found.</td></tr>';body.querySelectorAll('.appt-save').forEach(b=>b.onclick=()=>saveAppointment(b.dataset.id));body.querySelectorAll('.appt-delete').forEach(b=>b.onclick=()=>deleteAppointment(b.dataset.id));}
async function saveAppointment(id){const status=document.querySelector(`.appt-status[data-appt-id="${CSS.escape(id)}"]`);const note=document.querySelector(`.appt-note[data-note-id="${CSS.escape(id)}"]`);const r=await apptDb().from('appointments').update({status:status?.value||'Pending',admin_notes:note?.value?.trim()||null}).eq('id',id);if(r.error){alert('Unable to update appointment: '+r.error.message);return;}loadAppointments();}
async function deleteAppointment(id){if(!confirm('Delete this appointment?'))return;const r=await apptDb().from('appointments').delete().eq('id',id);if(r.error){alert('Unable to delete appointment: '+r.error.message);return;}loadAppointments();}
function openAppointments(){const b=document.querySelector('.side button[data-section="appointments"]');if(b)b.click();}
function injectAppointments(){if(document.getElementById('appointments'))return;document.head.insertAdjacentHTML('beforeend',ADMIN_APPT_STYLE);const nav=document.querySelector('.side');const main=document.querySelector('.main');const dashboard=document.getElementById('dashboard');if(!nav||!main)return;const b=document.createElement('button');b.dataset.section='appointments';b.type='button';b.textContent='🩺 Appointments';nav.appendChild(b);const s=document.createElement('section');s.id='appointments';s.className='section';s.innerHTML='<h2>Doctor Appointments</h2><div class="card"><p class="muted">Manage customer doctor appointment requests.</p><button id="refreshAppointments" class="btn primary" type="button">↻ Refresh</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Appointment</th><th>Patient</th><th>Doctor / Specialty</th><th>Date & Time</th><th>Reason</th><th>Status</th><th>Admin Notes</th><th>Action</th></tr></thead><tbody id="appointmentsBody"></tbody></table></div>';main.appendChild(s);b.addEventListener('click',function(){document.querySelectorAll('.side button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));s.classList.add('active');loadAppointments();});document.getElementById('refreshAppointments').onclick=loadAppointments;if(dashboard){const card=document.createElement('div');card.className='card stat appt-dashboard-card';card.title='Open Doctor Appointments';card.innerHTML='<div>🩺 Doctor Appointments</div><strong id="appointmentPendingCount">0</strong><span class="muted">Pending requests</span>';card.onclick=openAppointments;const grid=dashboard.querySelector('.grid');if(grid)grid.appendChild(card);}}
function boot(){injectAppointments();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.loadAppointments=loadAppointments;})();