(function(){
  const KEY='seema_medical_bills_v1';
  const STORE_NAME='ADITYA MEDICAL STORE';
  const STORE_SUBTITLE='Medicine Sales Invoice';
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>'₹'+Number(v||0).toFixed(2);
  const getBills=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return[]}};
  const saveBills=a=>localStorage.setItem(KEY,JSON.stringify(a));
  const invoiceNo=()=>`BILL-${Date.now().toString().slice(-8)}`;
  const db=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
  const style=`<style>.bill-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.bill-tabs button{border:0;border-radius:7px;padding:10px 14px;font-weight:700;cursor:pointer;background:#f2f4f7}.bill-tabs button.active{background:#123b2a;color:#fff}.bill-pane{display:none}.bill-pane.active{display:block}.bill-items{width:100%;border-collapse:collapse;margin-top:12px}.bill-items th,.bill-items td{padding:9px;border-bottom:1px solid #eee;text-align:left}.bill-total{text-align:right;font-size:20px;font-weight:700;margin-top:14px}.bill-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.bill-row{display:grid;grid-template-columns:2fr 1fr auto;gap:8px;align-items:end;margin-top:8px}.bill-history{width:100%;border-collapse:collapse}.bill-history th,.bill-history td{padding:9px;border-bottom:1px solid #eee;text-align:left}@media(max-width:700px){.bill-row{grid-template-columns:1fr 1fr}.bill-row button{grid-column:1/-1}}</style>`;
  function notify(t,ok=true){const x=document.getElementById('msg');if(x){x.textContent=t;x.className='card '+(ok?'success':'danger');setTimeout(()=>x.classList.add('hidden'),3000)}}
  async function medicines(){const r=await db.from('medicines').select('*').order('name');if(r.error){notify('Unable to load medicines: '+r.error.message,false);return[]}return r.data||[]}
  async function orders(){const r=await db.from('orders').select('*').order('created_at',{ascending:false});if(r.error){notify('Unable to load orders: '+r.error.message,false);return[]}return r.data||[]}
  function replaceBilling(){
    const s=document.getElementById('billing');if(!s||s.dataset.functional==='1')return;s.dataset.functional='1';
    s.innerHTML=style+`<h2>Billing & Invoices</h2><div class="bill-tabs"><button class="active" data-btab="offline">🧾 New Offline Sale</button><button data-btab="online">📦 Online Order → Bill</button><button data-btab="history">📚 Bill History</button></div><div id="bill-offline" class="bill-pane active card"></div><div id="bill-online" class="bill-pane card"></div><div id="bill-history" class="bill-pane card"></div>`;
    s.querySelectorAll('[data-btab]').forEach(b=>b.onclick=async()=>{s.querySelectorAll('[data-btab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');s.querySelectorAll('.bill-pane').forEach(x=>x.classList.remove('active'));document.getElementById('bill-'+b.dataset.btab).classList.add('active');if(b.dataset.btab==='offline')await renderOffline();if(b.dataset.btab==='online')await renderOnline();if(b.dataset.btab==='history')renderHistory()});
    renderOffline();renderOnline();renderHistory();
  }
  async function renderOffline(){const pane=document.getElementById('bill-offline');if(!pane)return;const meds=await medicines();pane.innerHTML=`<h3>New Offline Sale</h3><div class="formgrid"><label>Customer Name<input id="billCustomer" class="input" placeholder="Walk-in Customer"></label><label>Mobile<input id="billPhone" class="input" placeholder="Optional"></label><label>Payment Method<select id="billPayment" class="select"><option>Cash</option><option>UPI</option><option>Card</option></select></label><label>Medicine<select id="billMed" class="select"></select></label></div><div class="bill-row"><label>Quantity<input id="billQty" class="input" type="number" min="1" value="1"></label><div></div><button id="billAdd" class="btn primary" type="button">Add to Bill</button></div><div id="billCart"></div><div class="bill-actions"><button id="billSave" class="btn primary" type="button">Save Sale & Print Bill</button><button id="billClear" class="btn" type="button">Clear</button></div>`;const sel=document.getElementById('billMed');sel.innerHTML=meds.map(m=>`<option value="${esc(m.id)}">${esc(m.name)} — ${money(m.price)} — Stock ${Number(m.stock||0)}</option>`).join('')||'<option value="">No medicines available</option>';window._billCart=[];window._billMeds=meds;renderCart();
    const addSelected=()=>{const m=meds.find(x=>String(x.id)===String(sel.value)),q=Math.max(1,Number(document.getElementById('billQty').value||1));if(!m){notify('Select a medicine.',false);return}const old=window._billCart.find(x=>String(x.id)===String(m.id)),totalQ=(old?old.qty:0)+q;if(totalQ>Number(m.stock||0)){notify(`Only ${Number(m.stock||0)} units available for ${m.name}.`,false);return}if(old)old.qty=totalQ;else window._billCart.push({id:m.id,name:m.name,price:Number(m.price||0),qty:q});renderCart()};
    document.getElementById('billAdd').onclick=addSelected;
    sel.onchange=()=>{if(sel.value)addSelected()};
    document.getElementById('billClear').onclick=()=>{window._billCart=[];document.getElementById('billCustomer').value='';document.getElementById('billPhone').value='';renderCart()};document.getElementById('billSave').onclick=saveOffline}
  function renderCart(){const x=document.getElementById('billCart');if(!x)return;const a=window._billCart||[],total=a.reduce((s,i)=>s+i.price*i.qty,0);x.innerHTML=a.length?`<table class="bill-items"><thead><tr><th>Medicine</th><th>Qty</th><th>Rate</th><th>Amount</th><th></th></tr></thead><tbody>${a.map((i,n)=>`<tr><td>${esc(i.name)}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(i.price*i.qty)}</td><td><button class="btn danger" data-rm="${n}" type="button">Remove</button></td></tr>`).join('')}</tbody></table><div class="bill-total">Total: ${money(total)}</div>`:'<p class="muted">No medicines added to this bill.</p>';x.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{window._billCart.splice(Number(b.dataset.rm),1);renderCart()})}
  async function saveOffline(){const cart=window._billCart||[];if(!cart.length){const sel=document.getElementById('billMed');if(sel&&sel.value){const meds=window._billMeds||[],m=meds.find(x=>String(x.id)===String(sel.value));const q=Math.max(1,Number(document.getElementById('billQty').value||1));if(m&&q<=Number(m.stock||0)){window._billCart=[{id:m.id,name:m.name,price:Number(m.price||0),qty:q}];renderCart()}}}const finalCart=window._billCart||[];if(!finalCart.length){notify('Select a medicine and add it to the bill.',false);return}const customer=document.getElementById('billCustomer').value.trim()||'Walk-in Customer',phone=document.getElementById('billPhone').value.trim(),payment=document.getElementById('billPayment').value,total=finalCart.reduce((s,i)=>s+i.price*i.qty,0),fresh=await medicines();for(const i of finalCart){const m=fresh.find(x=>String(x.id)===String(i.id));if(!m||Number(m.stock||0)<i.qty){notify(`Insufficient stock for ${i.name}.`,false);return}}for(const i of finalCart){const m=fresh.find(x=>String(x.id)===String(i.id));const r=await db.from('medicines').update({stock:Number(m.stock||0)-i.qty}).eq('id',i.id);if(r.error){notify('Sale not saved: '+r.error.message,false);return}}const bill={invoice:invoiceNo(),type:'Offline Sale',date:new Date().toISOString(),customer,phone,payment,items:finalCart.map(i=>({...i})),total};const bills=getBills();bills.unshift(bill);saveBills(bills);notify('Offline sale saved.');printBill(bill);renderOffline();renderHistory()}
  async function renderOnline(){const p=document.getElementById('bill-online');if(!p)return;const os=await orders();window._billOrders=os;p.innerHTML=`<h3>Online Order → Bill</h3><p class="muted">Select an existing online order. Creating a bill does not change the order status or stock.</p><select id="onlineOrder" class="select"><option value="">Select order</option>${os.filter(o=>o.status!=='Cancelled').map(o=>`<option value="${esc(o.id)}">${esc(o.order_id)} — ${esc(o.customer_name)} — ${money(o.total)} — ${esc(o.status)}</option>`).join('')}</select><div id="onlinePreview" style="margin-top:12px"></div><div class="bill-actions"><button id="onlinePrint" class="btn primary" type="button">Create & Print Bill</button></div>`;document.getElementById('onlineOrder').onchange=previewOnline;document.getElementById('onlinePrint').onclick=createOnlineBill}
  function previewOnline(){const o=(window._billOrders||[]).find(x=>String(x.id)===String(document.getElementById('onlineOrder').value)),p=document.getElementById('onlinePreview');if(!o){p.innerHTML='';return}p.innerHTML=`<div class="card"><b>${esc(o.customer_name)}</b><br>${esc(o.phone||'')}<br>${esc(o.address||'')}<br><br>${(Array.isArray(o.items)?o.items:[]).map(i=>`${esc(i.name)} × ${Number(i.qty||0)} — ${money(Number(i.price||0)*Number(i.qty||0))}`).join('<br>')}<div class="bill-total">Total: ${money(o.total)}</div></div>`}
  function createOnlineBill(){const id=document.getElementById('onlineOrder').value,o=(window._billOrders||[]).find(x=>String(x.id)===String(id));if(!o){notify('Select an online order.',false);return}const bill={invoice:invoiceNo(),type:'Online Order',date:new Date().toISOString(),customer:o.customer_name,phone:o.phone||'',address:o.address||'',payment:o.payment_method||'COD',items:(Array.isArray(o.items)?o.items:[]).map(i=>({name:i.name,qty:Number(i.qty||0),price:Number(i.price||0)})),total:Number(o.total||0),orderId:o.order_id};const bills=getBills();bills.unshift(bill);saveBills(bills);notify('Online order bill created.');printBill(bill);renderHistory()}
  function renderHistory(){const p=document.getElementById('bill-history');if(!p)return;const bills=getBills();p.innerHTML=`<h3>Bill History</h3><input id="billSearch" class="input search" placeholder="Search invoice/customer"><div class="table-wrap"><table class="bill-history"><thead><tr><th>Invoice</th><th>Type</th><th>Customer</th><th>Amount</th><th>Payment</th><th>Date</th><th>Action</th></tr></thead><tbody id="billHistoryBody"></tbody></table></div>`;const render=()=>{const q=(document.getElementById('billSearch').value||'').toLowerCase(),a=bills.filter(b=>`${b.invoice} ${b.customer}`.toLowerCase().includes(q));document.getElementById('billHistoryBody').innerHTML=a.map(b=>`<tr><td>${esc(b.invoice)}</td><td>${esc(b.type)}</td><td>${esc(b.customer)}</td><td>${money(b.total)}</td><td>${esc(b.payment)}</td><td>${new Date(b.date).toLocaleString('en-IN')}</td><td><button class="btn primary" data-print="${esc(b.invoice)}" type="button">Print</button></td></tr>`).join('')||'<tr><td colspan="7">No bills found.</td></tr>';document.querySelectorAll('[data-print]').forEach(x=>x.onclick=()=>{const b=bills.find(y=>y.invoice===x.dataset.print);if(b)printBill(b)})};document.getElementById('billSearch').oninput=render;render()}
  function printBill(b){const rows=(b.items||[]).map(i=>`<tr><td>${esc(i.name)}</td><td>${Number(i.qty||0)}</td><td>${money(i.price)}</td><td>${money(Number(i.price||0)*Number(i.qty||0))}</td></tr>`).join('');const w=window.open('','_blank','width=800,height=900');if(!w){notify('Please allow pop-ups to print the bill.',false);return}w.document.write(`<!doctype html><html><head><title>${esc(b.invoice)}</title><style>body{font-family:Arial;margin:30px;color:#111}h1{text-align:center;margin-bottom:4px}.sub{text-align:center;color:#555}.meta{margin:20px 0}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #ddd;text-align:left}.total{text-align:right;font-size:20px;font-weight:bold;margin-top:18px}.foot{text-align:center;margin-top:35px;color:#555}</style></head><body><h1>${STORE_NAME}</h1><div class="sub">${STORE_SUBTITLE}</div><div class="meta"><b>Invoice:</b> ${esc(b.invoice)}<br><b>Date:</b> ${new Date(b.date).toLocaleString('en-IN')}<br><b>Customer:</b> ${esc(b.customer)}<br><b>Mobile:</b> ${esc(b.phone||'—')}<br><b>Payment:</b> ${esc(b.payment||'—')}${b.orderId?`<br><b>Online Order:</b> ${esc(b.orderId)}`:''}</div><table><thead><tr><th>Medicine</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${rows}</tbody></table><div class="total">Grand Total: ${money(b.total)}</div><div class="foot">Thank you for purchasing from ${STORE_NAME}.</div><script>window.onload=function(){window.print()}<\/script></body></html>`);w.document.close()}
  function watch(){replaceBilling();const ob=new MutationObserver(()=>replaceBilling());ob.observe(document.body,{childList:true,subtree:true})}
  window.addEventListener('load',watch);setTimeout(watch,500);
})();