// Seema Medical Store - SINGLE CART SYSTEM v7
(function(){
'use strict';
let seemaCart=[];
const KEY='seema_cart_final_v2';
function getProducts(){try{return products;}catch(e){return[]}}
function read(){try{const a=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(a)?a.filter(x=>x&&x.id).map(x=>({id:String(x.id),q:Math.max(1,Number(x.q)||1)})):[]}catch(e){return[]}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(seemaCart));}catch(e){}}
function idx(id){return getProducts().findIndex(p=>String(p[4]?.id)===String(id))}
function importLegacy(){try{const ps=getProducts();if(Array.isArray(cart)&&cart.length){for(const x of cart){const p=ps[x.i];if(!p?.[4]?.id)continue;const id=String(p[4].id),q=Math.max(1,Number(x.q)||1),old=seemaCart.find(a=>a.id===id);if(old)old.q=Math.max(old.q,q);else seemaCart.push({id,q});}cart.length=0;save();}}catch(e){}}
function syncLegacy(){try{const ps=getProducts();cart.length=0;seemaCart.forEach(x=>{const i=idx(x.id);if(i>=0)cart.push({i,q:x.q})})}catch(e){}}
function render(){importLegacy();const ps=getProducts();seemaCart=seemaCart.filter(x=>idx(x.id)>=0);save();let count=0,total=0;const html=seemaCart.map(x=>{const i=idx(x.id),p=ps[i];if(!p)return'';const price=Number(p[3])||0;count+=x.q;total+=price*x.q;return `<div class="cart-row"><div><strong>${p[1]}</strong><div class="small">${p[2]}</div></div><div class="qty"><button type="button" data-seema-cart="minus" data-id="${x.id}">−</button> ${x.q} <button type="button" data-seema-cart="plus" data-id="${x.id}">+</button></div><strong>₹${(price*x.q).toFixed(2)}</strong></div>`}).join('');const c=document.getElementById('cartCount'),t=document.getElementById('cartTotal'),box=document.getElementById('cartItems'),more=document.getElementById('cartAddMoreButton');if(c)c.textContent=count;if(t)t.textContent='₹'+total.toFixed(2);if(box)box.innerHTML=html||"<p class='muted'>Your cart is empty.</p>";if(more)more.hidden=seemaCart.length===0;syncLegacy()}
function add(id){const ps=getProducts(),i=idx(id);if(i<0)return;const m=ps[i][4],stock=Number(m.stock??0);if(stock<=0){alert('This medicine is currently out of stock.');return}const x=seemaCart.find(a=>a.id===String(id));if(x){if(x.q>=stock){alert('Only '+stock+' unit(s) available.');return}x.q++}else seemaCart.push({id:String(id),q:1});save();render()}
function quantity(id,d){const x=seemaCart.find(a=>a.id===String(id));if(!x)return;const i=idx(id),ps=getProducts(),stock=Number(ps[i]?.[4]?.stock??0);if(d>0&&x.q>=stock){alert('Only '+stock+' unit(s) available.');return}x.q+=d;if(x.q<=0)seemaCart=seemaCart.filter(a=>a!==x);save();render()}
function total(){const ps=getProducts();return seemaCart.reduce((s,x)=>{const i=idx(x.id);return s+(Number(ps[i]?.[3])||0)*x.q},0)}
function bind(){document.querySelectorAll('#productGrid .product .add').forEach(b=>{if(b.dataset.seemaBound)return;const m=(b.getAttribute('onclick')||'').match(/addToCart\((\d+)\)/);if(!m)return;const p=getProducts()[Number(m[1])];if(!p?.[4]?.id)return;b.dataset.seemaId=String(p[4].id);b.dataset.seemaBound='1';b.removeAttribute('onclick')})}
document.addEventListener('click',function(e){const b=e.target.closest?.('#productGrid .product .add');if(b&&b.dataset.seemaId){e.preventDefault();e.stopImmediatePropagation();add(b.dataset.seemaId);return}const q=e.target.closest?.('[data-seema-cart]');if(q){e.preventDefault();e.stopImmediatePropagation();quantity(q.dataset.id,q.dataset.seemaCart==='plus'?1:-1)}},true);
window.addToCart=function(i){const p=getProducts()[i];if(p?.[4]?.id)add(p[4].id)};
window.changeQty=function(i,d){const p=getProducts()[i];if(p?.[4]?.id)quantity(p[4].id,d)};
window.updateCart=render;
window.total=total;
window.addMoreMedicines=function(){document.getElementById('cartOverlay')?.classList.remove('open');document.getElementById('products')?.scrollIntoView({behavior:'smooth',block:'start'})};
window.openCheckout=function(){render();if(!seemaCart.length){alert('Please add at least one product.');return}document.getElementById('cartOverlay')?.classList.remove('open');if(typeof resetCheckoutForm==='function')resetCheckoutForm();const ps=getProducts(),items=document.getElementById('checkoutItems');if(items)items.innerHTML=seemaCart.map(x=>{const p=ps[idx(x.id)];return `<div class="summary-line"><span>${p[1]} × ${x.q}</span><span>₹${((Number(p[3])||0)*x.q).toFixed(2)}</span></div>`}).join('');const ct=document.getElementById('checkoutTotal');if(ct)ct.textContent='₹'+total().toFixed(2);if(typeof togglePaymentFields==='function')togglePaymentFields();if(typeof updateUpiLink==='function')updateUpiLink();document.getElementById('checkoutOverlay')?.classList.add('open')};
seemaCart=read();render();window.addEventListener('load',function(){bind();render()});setInterval(function(){try{if(Array.isArray(cart)&&cart.length){importLegacy();render()}else bind()}catch(e){}},150);const grid=document.getElementById('productGrid');if(grid)new MutationObserver(bind).observe(grid,{childList:true,subtree:true});
})();