// Seema Medical Store - Single Authoritative Cart V4
(function(){'use strict';
const KEY='seema_cart_v3', USER_PREFIX='seema_cart_v3_user_';
function read(key=KEY){try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v:[]}catch(e){return[]}}
function write(value,key=KEY){try{localStorage.setItem(key,JSON.stringify(value));window.dispatchEvent(new Event('cartUpdated'));return true}catch(e){console.error('CART V4 SAVE ERROR',e);return false}}
function valid(){return Array.isArray(window.products)&&typeof cart!=='undefined'}
function fromStorage(){if(!valid())return;const saved=read(),next=[];saved.forEach(x=>{const i=products.findIndex(p=>String(p?.[4]?.id)===String(x.id));if(i<0)return;const stock=Number(products[i][4]?.stock??0);if(stock<=0)return;next.push({i,q:Math.min(Math.max(1,Number(x.q)||1),stock)})});cart.length=0;next.forEach(x=>cart.push(x));render()}
function snapshot(){if(!valid())return[];return cart.map(x=>{const p=products[x.i];return p?.[4]?.id?{id:p[4].id,q:Math.max(1,Number(x.q)||1)}:null}).filter(Boolean)}
function persist(){const data=snapshot();write(data);const auth=window.seemaCustomerAuth;if(auth?.auth?.getSession)auth.auth.getSession().then(({data:s})=>{const id=s?.session?.user?.id;if(id)write(data,USER_PREFIX+id)}).catch(()=>{});return data}
function render(){if(!valid())return;let count=0,total=0;const rows=cart.map(x=>{const p=products[x.i];if(!p)return '';const q=Number(x.q)||1,price=Number(p[3])||0;count+=q;total+=price*q;return `<div class="cart-row"><div><strong>${p[1]}</strong><div class="small">${p[2]}</div></div><div class="qty"><button type="button" onclick="changeQty(${x.i},-1)">−</button> ${q} <button type="button" onclick="changeQty(${x.i},1)">+</button></div><strong>₹${(price*q).toFixed(2)}</strong></div>`}).join('');const c=document.getElementById('cartCount');if(c)c.textContent=count;const t=document.getElementById('cartTotal');if(t)t.textContent='₹'+total.toFixed(2);const items=document.getElementById('cartItems');if(items)items.innerHTML=rows||"<p class='muted'>Your cart is empty.</p>";const more=document.getElementById('cartAddMoreButton');if(more)more.hidden=cart.length===0}
function add(i){if(!valid())return;const p=products[i];if(!p)return;const stock=Number(p[4]?.stock??0);if(stock<=0){alert('This medicine is currently out of stock.');return}const x=cart.find(v=>Number(v.i)===Number(i));if(x){if(x.q>=stock){alert('Only '+stock+' unit(s) available.');return}x.q++}else cart.push({i:Number(i),q:1});persist();render()}
function qty(i,d){if(!valid())return;const x=cart.find(v=>Number(v.i)===Number(i));if(!x)return;const stock=Number(products[i]?.[4]?.stock??0);if(d>0&&x.q>=stock){alert('Only '+stock+' unit(s) available.');return}x.q+=Number(d);if(x.q<=0)cart.splice(cart.indexOf(x),1);persist();render()}
function open(){const o=document.getElementById('cartOverlay');if(!o)return;fromStorage();o.classList.add('open');o.style.display='flex';o.setAttribute('aria-hidden','false')}
function close(e){const o=document.getElementById('cartOverlay');if(!o)return;if(!e||e.target===o){o.classList.remove('open');o.style.removeProperty('display');o.setAttribute('aria-hidden','true')}}
function restoreUser(id){if(!id)return;const saved=read(USER_PREFIX+id);write(saved);fromStorage()}
function parkUser(id){if(id)write(snapshot(),USER_PREFIX+id);write([]);if(valid()){cart.length=0;render()}window.dispatchEvent(new Event('cartLogoutHide'))}
window.addToCart=add;window.changeQty=qty;window.updateCart=function(){render();persist()};window.openCart=open;window.closeCart=close;window.openCartPanel=open;window.reloadCartFromStorage=fromStorage;window.cartV4RestoreForUser=restoreUser;window.cartV4ParkForUser=parkUser;window.cartV4Read=()=>read();window.cartV4Key=KEY;
window.addEventListener('medicinesReady',fromStorage);window.addEventListener('storage',e=>{if(e.key===KEY)fromStorage()});document.addEventListener('DOMContentLoaded',()=>{fromStorage();const b=document.getElementById('mainCartButton');if(b&&!b.dataset.v4Bound){b.dataset.v4Bound='1';b.addEventListener('click',e=>{e.preventDefault();open()},true)}const o=document.getElementById('cartOverlay');if(o)o.addEventListener('click',e=>{if(e.target===o)close(e)},true)});window.addEventListener('beforeunload',persist);
})();