(function(){'use strict';
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let salesChart=null,ordersChart=null,productChart=null,categoryChart=null,lastRows=[];
const periods={daily:{label:'Daily',count:30,step:'day'},weekly:{label:'Weekly',count:12,step:'week'},monthly:{label:'Monthly',count:12,step:'month'},quarterly:{label:'Quarterly',count:8,step:'quarter'},halfyearly:{label:'Half-Yearly',count:6,step:'half'},annually:{label:'Annually',count:5,step:'year'}};
function indiaParts(d){const a=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(d));const o={};a.forEach(x=>o[x.type]=x.value);return{y:+o.year,m:+o.month,d:+o.day};}
function keyFor(d,step){const p=indiaParts(d);if(step==='day')return `${p.y}-${String(p.m).padStart(2,'0')}-${String(p.d).padStart(2,'0')}`;if(step==='week'){const x=new Date(Date.UTC(p.y,p.m-1,p.d));const day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()-day+1);return x.toISOString().slice(0,10)}if(step==='month')return `${p.y}-${String(p.m).padStart(2,'0')}`;if(step==='quarter')return `${p.y}-Q${Math.floor((p.m-1)/3)+1}`;if(step==='half')return `${p.y}-H${p.m<=6?1:2}`;return String(p.y)}
function startLabel(k,step){if(step==='day'){const [y,m,d]=k.split('-');return new Date(Date.UTC(+y,+m-1,+d)).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}if(step==='week'){const [y,m,d]=k.split('-');return 'Wk '+new Date(Date.UTC(+y,+m-1,+d)).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}return k}
function buildBuckets(step,count){const now=new Date(),out=[];let p=indiaParts(now);let y=p.y,m=p.m;for(let i=count-1;i>=0;i--){if(step==='day'){const x=new Date(Date.UTC(y,m-1,p.d-i));out.push(keyFor(x,'day'));}else if(step==='week'){const x=new Date(Date.UTC(y,m-1,p.d-i*7));out.push(keyFor(x,'week'));}else if(step==='month'){let mm=m-i,yy=y;while(mm<=0){mm+=12;yy--}out.push(`${yy}-${String(mm).padStart(2,'0')}`);}else if(step==='quarter'){let q=Math.floor((m-1)/3)+1-i,yy=y;while(q<=0){q+=4;yy--}out.push(`${yy}-Q${q}`);}else if(step==='half'){let h=m<=6?1:2-i,yy=y;while(h<=0){h+=2;yy--}out.push(`${yy}-H${h}`);}else out.push(String(y-i));}return [...new Set(out)];}
function getRows(){const mode=document.getElementById('salesBasis')?.value||'all';return (window.__adityaOrders||[]).filter(o=>o&&o.created_at&&o.status!=='Cancelled'&&(mode!=='delivered'||o.status==='Delivered'));}
function currentPeriod(){return document.getElementById('reportPeriod')?.value||'monthly'}
function refresh(){if(!document.getElementById('salesReportRoot'))return;const cfg=periods[currentPeriod()],rows=getRows(),keys=buildBuckets(cfg.step,cfg.count),map={};keys.forEach(k=>map[k]={key:k,sales:0,orders:0});rows.forEach(o=>{const k=keyFor(o.created_at,cfg.step);if(!map[k])return;map[k].orders++;map[k].sales+=Number(o.total||0)});lastRows=keys.map(k=>map[k]);const total=rows.reduce((s,o)=>s+Number(o.total||0),0),del=rows.filter(o=>o.status==='Delivered').length;document.getElementById('reportSales').textContent=money(total);document.getElementById('reportOrders').textContent=rows.length;document.getElementById('reportAvg').textContent=money(rows.length?total/rows.length:0);document.getElementById('reportDelivered').textContent=del;drawCharts();drawProducts(rows);drawCategories(rows);}
function drawCharts(){if(!window.Chart)return;const labels=lastRows.map(x=>startLabel(x.key,periods[currentPeriod()].step)),sales=lastRows.map(x=>x.sales),oc=lastRows.map(x=>x.orders);if(salesChart)salesChart.destroy();if(ordersChart)ordersChart.destroy();salesChart=new Chart(document.getElementById('salesTrendChart'),{type:'line',data:{labels,datasets:[{label:'Sales',data:sales,tension:.25,fill:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{callback:v=>'₹'+Number(v).toLocaleString('en-IN')}}}}});ordersChart=new Chart(document.getElementById('ordersTrendChart'),{type:'bar',data:{labels,datasets:[{label:'Orders',data:oc}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,precision:0}}}})}
function itemRows(rows){const a=[];rows.forEach(o=>(Array.isArray(o.items)?o.items:[]).forEach(i=>a.push({name:i.name||'Unknown',qty:Number(i.qty||0),amount:Number(i.price||0)*Number(i.qty||0)})));return a}
function drawProducts(rows){if(!window.Chart)return;const map={};itemRows(rows).forEach(i=>{map[i.name]=(map[i.name]||0)+i.amount});const top=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,10);if(productChart)productChart.destroy();productChart=new Chart(document.getElementById('topProductsChart'),{type:'bar',data:{labels:top.map(x=>x[0]),datasets:[{label:'Sales',data:top.map(x=>x[1])}]},options:{indexAxis:'y',responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,ticks:{callback:v=>'₹'+Number(v).toLocaleString('en-IN')}}}}})}
function drawCategories(rows){if(!window.Chart)return;const map={};itemRows(rows).forEach(i=>{const med=(window.__adityaMedicines||[]).find(m=>String(m.id)===String(i.medicine_id)||String(m.name).toLowerCase()===String(i.name).toLowerCase());const c=med?.category||i.category||'Other';map[c]=(map[c]||0)+i.amount});const top=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8);if(categoryChart)categoryChart.destroy();categoryChart=new Chart(document.getElementById('categorySalesChart'),{type:'doughnut',data:{labels:top.map(x=>x[0]),datasets:[{data:top.map(x=>x[1])}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}})}
function exportReport(){const cfg=periods[currentPeriod()],rows=lastRows.map(x=>[x.key,x.orders,x.sales]);const csv=[['Period','Orders','Sales'],...rows].map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`aditya-medical-store-${currentPeriod()}-sales-report.csv`;a.click();}
function mount(){const s=document.getElementById('sales');if(!s||document.getElementById('salesReportRoot'))return;const root=document.createElement('div');root.id='salesReportRoot';root.innerHTML=`<style>#salesReportRoot{margin-top:18px}.report-controls{display:flex;gap:10px;flex-wrap:wrap;align-items:end;margin-bottom:14px}.report-controls label{font-weight:700;min-width:160px}.report-controls select{display:block;margin-top:5px}.report-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.report-chart-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.report-chart{height:340px}.report-chart canvas{width:100%!important;height:100%!important}@media(max-width:800px){.report-grid,.report-chart-grid{grid-template-columns:1fr}}</style><div class="card"><h3>Sales Analysis</h3><div class="report-controls"><label>Report Period<select id="reportPeriod" class="select"><option value="daily">Daily — last 30 days</option><option value="weekly">Weekly — last 12 weeks</option><option value="monthly" selected>Monthly — last 12 months</option><option value="quarterly">Quarterly — last 8 quarters</option><option value="halfyearly">Half-Yearly — last 6 periods</option><option value="annually">Annually — last 5 years</option></select></label><label>Sales Basis<select id="salesBasis" class="select"><option value="all">All non-cancelled orders</option><option value="delivered">Delivered orders only</option></select></label><button id="exportSalesReport" class="btn primary" type="button">📥 Export Report CSV</button></div><div class="report-grid"><div class="card stat">Sales<strong id="reportSales">₹0.00</strong></div><div class="card stat">Orders<strong id="reportOrders">0</strong></div><div class="card stat">Average Order<strong id="reportAvg">₹0.00</strong></div><div class="card stat">Delivered<strong id="reportDelivered">0</strong></div></div></div><div class="report-chart-grid"><div class="card"><h3>Sales Trend</h3><div class="report-chart"><canvas id="salesTrendChart"></canvas></div></div><div class="card"><h3>Order Trend</h3><div class="report-chart"><canvas id="ordersTrendChart"></canvas></div></div><div class="card"><h3>Top 10 Products by Sales</h3><div class="report-chart"><canvas id="topProductsChart"></canvas></div></div><div class="card"><h3>Sales by Medicine Category</h3><div class="report-chart"><canvas id="categorySalesChart"></canvas></div></div></div>`;s.appendChild(root);document.getElementById('reportPeriod').onchange=refresh;document.getElementById('salesBasis').onchange=refresh;document.getElementById('exportSalesReport').onclick=exportReport;refresh();}
function sync(){window.__adityaOrders=window.__adityaOrders||[];try{if(typeof orders!=='undefined')window.__adityaOrders=orders||[]}catch(e){}try{if(typeof medicines!=='undefined')window.__adityaMedicines=medicines||[]}catch(e){}if(document.getElementById('sales')?.classList.contains('active'))refresh();}
function boot(){mount();sync();setInterval(sync,1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.addEventListener('load',boot);
})();