const products = [];
let cart=[],activeCategory="All";
const ANAND_UPI_ID="7007596728@ptyes";
const ANAND_UPI_NAME="ANAND ENTERPRISES";
let medicineLoadError="";

async function loadMedicines(){
  const grid=document.getElementById("productGrid");
  try{
    if(!window.supabase||!window.SUPABASE_URL||!window.SUPABASE_ANON_KEY) throw new Error("Supabase connection is missing.");
    const db=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
    const {data,error}=await db.from("medicines").select("id,name,category,price,stock,manufacturer,expiry_date").order("name");
    if(error) throw error;
    products.length=0;
    (data||[]).forEach(m=>{const category=String(m.category||"Other").trim()||"Other";products.push([category,m.name,"Available stock: "+(m.stock??0),Number(m.price)||0,m])});
    buildCategories();renderProducts();window.dispatchEvent(new Event("medicinesReady"));processMedicineDeepLink();
  }catch(error){medicineLoadError=error.message||"Unable to load medicines.";console.error("MEDICINE LOAD ERROR",error);buildCategories();grid.innerHTML='<p>Unable to load medicines. Please refresh the page.</p>'}
}
function buildCategories(){const tabBox=document.getElementById("categoryTabs");if(!tabBox)return;const seen=new Map();products.forEach(p=>{const name=String(p[0]||"Other").trim()||"Other",key=name.toLowerCase();if(!seen.has(key))seen.set(key,name)});const categories=[...seen.values()].sort((a,b)=>a.localeCompare(b,"en",{sensitivity:"base"}));if(activeCategory!=="All"&&!categories.some(c=>c.toLowerCase()===String(activeCategory).toLowerCase()))activeCategory="All";tabBox.innerHTML=["All",...categories].map(c=>`<button type="button" class="tab ${activeCategory.toLowerCase()===c.toLowerCase()?"active":""}" data-category="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join("");tabBox.querySelectorAll(".tab").forEach(button=>button.addEventListener("click",()=>setCategory(button.dataset.category)))}
function escapeHtml(value){return String(value??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function setCategory(c){activeCategory=String(c||"All");document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",String(b.dataset.category||b.textContent).toLowerCase()===activeCategory.toLowerCase()));renderProducts()}
function renderProducts(){const q=(document.getElementById("search")?.value||"").toLowerCase();const f=products.filter(p=>(activeCategory.toLowerCase()==="all"||String(p[0]).toLowerCase()===activeCategory.toLowerCase())&&(p[1]+" "+p[0]+" "+(p[4]?.manufacturer||"")).toLowerCase().includes(q));document.getElementById("productGrid").innerHTML=f.map(p=>{const i=products.indexOf(p),stock=Number(p[4]?.stock??0);return `<article class="product"><div class="category">${escapeHtml(p[0])}</div><h3>${escapeHtml(p[1])}</h3><p>${escapeHtml(p[2])}</p>${p[4]?.manufacturer?`<p class="small">${escapeHtml(p[4].manufacturer)}</p>`:""}<div class="product-bottom"><span class="price">${p[3]?"₹"+p[3]:"Check price"}</span><button class="add" ${stock<=0?"disabled":""} onclick="addToCart(${i})">${stock<=0?"Out of Stock":"Add"}</button></div></article>`}).join("")||"<p>No medicine found.</p>"}
function processMedicineDeepLink(){const params=new URLSearchParams(window.location.search),id=params.get("addMedicineId");if(!id)return;const i=products.findIndex(p=>String(p[4]?.id)===String(id));if(i<0){alert("Medicine is not available.");history.replaceState({},document.title,"index.html#products");return}const stock=Number(products[i][4]?.stock??0),price=Number(products[i][3]||0);if(stock<=0||price<=0){alert("This medicine is currently unavailable or its store price has not been set.");history.replaceState({},document.title,"index.html#products");return}if(typeof window.addToCart!="function"){alert("Cart is still loading. Please try again.");return}window.addToCart(i);history.replaceState({},document.title,"index.html#products");setTimeout(openCart,150)}
function addToCart(i){const stock=Number(products[i][4]?.stock??0),f=cart.find(x=>x.i===i);if(stock<=0)return;if(f&&f.q>=stock){alert("Only "+stock+" unit(s) available.");return}if(f)f.q++;else cart.push({i,q:1});updateCart()}
function changeQty(i,d){const x=cart.find(x=>x.i===i);if(!x)return;const stock=Number(products[i][4]?.stock??0);if(d>0&&x.q>=stock){alert("Only "+stock+" unit(s) available.");return}x.q+=d;if(x.q<=0)cart=cart.filter(y=>y.i!==i);updateCart()}
function total(){return cart.reduce((s,x)=>s+(Number(products[x.i][3])||0)*x.q,0)}
function updateCart(){document.getElementById("cartCount").textContent=cart.reduce((s,x)=>s+x.q,0);document.getElementById("cartTotal").textContent="₹"+total();document.getElementById("cartItems").innerHTML=cart.length?cart.map(x=>`<div class="cart-row"><div><strong>${products[x.i][1]}</strong><div class="small">${products[x.i][2]}</div></div><div class="qty"><button onclick="changeQty(${x.i},-1)">−</button> ${x.q} <button onclick="changeQty(${x.i},1)">+</button></div><strong>₹${(Number(products[x.i][3])||0)*x.q}</strong></div>`).join(""):"<p class='muted'>Your cart is empty.</p>"}
function openCart(){document.getElementById("cartOverlay").classList.add("open")}
function closeCart(e){if(!e||e.target===document.getElementById("cartOverlay"))document.getElementById("cartOverlay").classList.remove("open")}
function resetCheckoutForm(){const form=document.getElementById("orderForm"),success=document.getElementById("orderSuccess");if(form){form.hidden=false;form.reset()}if(success){success.hidden=true;success.innerHTML=""}togglePaymentFields();updateUpiLink()}
function openCheckout(){if(!cart.length){alert("Please add at least one product.");return}document.getElementById("cartOverlay").classList.remove("open");resetCheckoutForm();document.getElementById("checkoutItems").innerHTML=cart.map(x=>`<div class="summary-line"><span>${products[x.i][1]} × ${x.q}</span><span>₹${(Number(products[x.i][3])||0)*x.q}</span></div>`).join("");document.getElementById("checkoutTotal").textContent="₹"+total();togglePaymentFields();updateUpiLink();document.getElementById("checkoutOverlay").classList.add("open")}
function closeCheckout(e){if(!e||e.target===document.getElementById("checkoutOverlay"))document.getElementById("checkoutOverlay").classList.remove("open")}
function updateUpiLink(){const button=document.getElementById("upiPayButton");if(!button)return;const amount=total();button.href="upi://pay?pa="+encodeURIComponent(ANAND_UPI_ID)+"&pn="+encodeURIComponent(ANAND_UPI_NAME)+"&am="+amount.toFixed(2)+"&cu=INR"}
function togglePaymentFields(){const method=document.getElementById("paymentMethod")?.value;const upi=document.getElementById("upiPaymentFields"),cod=document.getElementById("codPaymentFields"),txn=document.getElementById("txn");if(!upi||!cod)return;if(method==="COD"){upi.hidden=true;cod.hidden=false;if(txn)txn.required=false}else{upi.hidden=false;cod.hidden=true;if(txn)txn.required=true;updateUpiLink()}}
loadMedicines();updateCart();togglePaymentFields();