create table if not exists public.medicines (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  price numeric(10,2) not null default 0,
  stock integer not null default 0,
  manufacturer text,
  expiry_date date,
  created_at timestamptz not null default now()
);

alter table public.medicines enable row level security;

create policy "Authenticated admin can manage medicines"
on public.medicines
for all
to authenticated
using (auth.email() = 'a81650448@gmail.com')
with check (auth.email() = 'a81650448@gmail.com');
