create table if not exists public.medicines (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  price numeric(10,2) not null default 0,
  stock integer not null default 0,
  manufacturer text,
  expiry_date date,
  created_at timestamptz not null default now()
);

alter table public.medicines enable row level security;

create policy "Authenticated admin can manage medicines"
on public.medicines
for all
to authenticated
using (auth.email() = 'a81650448@gmail.com')
with check (auth.email() = 'a81650448@gmail.com');


-- The customer-facing GitHub Pages site uses the Supabase anon/publishable key.
-- Allow public READ access to the medicine catalogue while keeping INSERT/UPDATE/DELETE
-- restricted to the configured authenticated admin policy above.
drop policy if exists "Public can view medicines" on public.medicines;
create policy "Public can view medicines"
on public.medicines
for select
to anon, authenticated
using (true);

grant select on public.medicines to anon, authenticated;
